#!/bin/bash
#BSUB -J ipengine
#BSUB -W 48:00
#BSUB -R scratch
#BSUB -o /scratch/dmanik/ipyparalleltmp/ipengine.%J
#BSUB -n {n}
#BSUB -q {queue}
#BSUB -a openmpi
mpirun.lsf ipengine --profile-dir="{profile_dir}"
